-- SQL to create the order_prefix table for Menha Boutique
-- Run this in your Supabase SQL Editor

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.order_prefix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    prefix TEXT DEFAULT 'ORD' NOT NULL,
    next_sequence BIGINT DEFAULT 1000 NOT NULL
);

-- 2. Insert the initial configuration
INSERT INTO public.order_prefix (prefix, next_sequence)
VALUES ('ORD', 1000)
ON CONFLICT DO NOTHING;

-- 3. Enable RLS (Row Level Security)
ALTER TABLE public.order_prefix ENABLE ROW LEVEL SECURITY;

-- 4. Create policies (Allow reading and updating by the anon key for simplicity in this project)
-- NOTE: In a production app, you might want to restrict update to authenticated admins only.
CREATE POLICY "Allow public read access" ON public.order_prefix
    FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow public update access" ON public.order_prefix
    FOR UPDATE TO anon, authenticated USING (true);

-- 5. Grant permissions to the anon/authenticated roles
GRANT ALL ON public.order_prefix TO anon, authenticated, service_role;

-- ============================================================
-- 6. Tracking columns on orders (for admin to set, customer to see)
-- ============================================================
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS tracking_id TEXT,
    ADD COLUMN IF NOT EXISTS tracking_url TEXT;

-- ============================================================
-- 7. Variant image column on product_attributes
-- ============================================================
ALTER TABLE public.product_attributes
    ADD COLUMN IF NOT EXISTS image_url TEXT;

-- ============================================================
-- 8. One-time cleanup: remove duplicate variants per product
--    (Keeps the lowest id for each (product_id, attribute_value) pair)
--    Run only if you already accumulated duplicates from prior saves.
--    Step 8a repoints existing order_items so the FK doesn't block step 8b.
-- ============================================================

-- 8a. Repoint order_items.attribute_id from each duplicate to the surviving (lowest-id) variant
WITH dupes AS (
    SELECT
        a.id AS dup_id,
        (
            SELECT MIN(b.id)
            FROM public.product_attributes b
            WHERE b.product_id      = a.product_id
              AND b.attribute_type  = a.attribute_type
              AND b.attribute_value = a.attribute_value
        ) AS keep_id
    FROM public.product_attributes a
    WHERE EXISTS (
        SELECT 1
        FROM public.product_attributes b
        WHERE b.product_id      = a.product_id
          AND b.attribute_type  = a.attribute_type
          AND b.attribute_value = a.attribute_value
          AND b.id < a.id
    )
)
UPDATE public.order_items oi
SET attribute_id = d.keep_id
FROM dupes d
WHERE oi.attribute_id = d.dup_id;

-- 8b. Now the duplicates are no longer referenced — delete them.
DELETE FROM public.product_attributes a
USING public.product_attributes b
WHERE a.product_id      = b.product_id
  AND a.attribute_type  = b.attribute_type
  AND a.attribute_value = b.attribute_value
  AND a.id > b.id;

-- 8c. Same idea for product_images: dedupe (product_id, image_url).
--     order_items doesn't reference product_images so no repointing needed.
DELETE FROM public.product_images a
USING public.product_images b
WHERE a.product_id = b.product_id
  AND a.image_url  = b.image_url
  AND a.id > b.id;

-- ============================================================
-- 9. Make sure DELETE is permitted on product_attributes/product_images
--    (the admin UI relies on this for variant edits)
--    Skip if your RLS is already configured.
-- ============================================================
-- ALTER TABLE public.product_attributes ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow admin delete" ON public.product_attributes FOR DELETE TO anon, authenticated USING (true);
-- ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow admin delete" ON public.product_images FOR DELETE TO anon, authenticated USING (true);

-- ============================================================
-- 10. Contact messages table (for the Contact Us form)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    phone TEXT,
    subject TEXT,
    message TEXT
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert (contact form is public)
CREATE POLICY "Allow public insert" ON public.contact_messages
    FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Allow admin (anon key) to read and delete
CREATE POLICY "Allow public read" ON public.contact_messages
    FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow public delete" ON public.contact_messages
    FOR DELETE TO anon, authenticated USING (true);

GRANT ALL ON public.contact_messages TO anon, authenticated, service_role;
